global using InvoicesManager.Classes;
global using InvoicesManager.Classes.Enums;
global using InvoicesManager.Core;
global using InvoicesManager.Models;
global using InvoicesManager.Windows;
global using InvoicesManager.Views;
global using System.Windows;
global using System.Windows.Forms;
global using System;
global using System.Windows.Controls;
global using System.IO;
global using Application = System.Windows.Application;
global using MessageBox = System.Windows.MessageBox;
global using RadioButton = System.Windows.Controls.RadioButton;
global using Button = System.Windows.Controls.Button;
global using ComboBox = System.Windows.Controls.ComboBox;
global using Clipboard = System.Windows.Clipboard;
global using Newtonsoft.Json;
global using System.Collections.Generic;
global using System.Data;
global using System.Diagnostics;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Threading;
global using System.Security.Cryptography;